# Homework 01, Module 01, Data Science
1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [4]:
import numpy as np

In [5]:
b = np.arange(1, 11, 1)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
a = np.linspace(1, 10, num=10, dtype=int)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [11]:
a = np.zeros((3, 3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [24]:
a = np.random.randint(1, 11, (5,5))
print(a)

[[ 5 10  5  1  6]
 [ 8  1  1  3  7]
 [ 8  5  5  8  6]
 [ 6  8  7  5 10]
 [ 1  4 10  6  6]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [28]:
a = np.random.random((4,4))
print(a)

[[0.02220725 0.48382108 0.96154165 0.07810755]
 [0.18642482 0.72884093 0.95194963 0.56598962]
 [0.43314937 0.99912058 0.56752542 0.61286171]
 [0.22479248 0.59973824 0.64491589 0.47645512]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [32]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11 , 5)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[9 5 2 1 7]
[9 2 1 7 8]
[18  7  3  8 15]
[ 0  3  1 -6 -1]
[81 10  2  7 56]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [45]:
a = np.random.random(7)
b = np.random.random(7)
print(a)
print(b)
print(np.dot(a, b))

[0.75040986 0.66901324 0.46775286 0.20484909 0.49076589 0.37238469
 0.47740115]
[0.36589039 0.83791799 0.76864751 0.31399468 0.57262533 0.27604905
 0.45284293]
1.8590137376766824


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [51]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 3))
print(f'matrix A:\n{a}')
print(f'matrix B:\n{b}')
print('AxB:')
print(np.dot(a, b))

matrix A:
[[3 5]
 [2 7]]
matrix B:
[[ 2  6  2]
 [ 7 10  9]]
AxB:
[[41 68 51]
 [53 82 67]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [52]:
a = np.random.randint(1, 11, (3, 3))
print(a)
print(np.linalg.inv(a))

[[ 7  6 10]
 [ 8  6  5]
 [10  7  9]]
[[-0.48717949 -0.41025641  0.76923077]
 [ 0.56410256  0.94871795 -1.15384615]
 [ 0.1025641  -0.28205128  0.15384615]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [57]:
a = np.random.random((4, 4))
print(f'matrix A:\n{a}')
print(f'matrix A^T:\n{a.T}')

matrix A:
[[0.6096148  0.87262718 0.02390303 0.27159522]
 [0.27721958 0.12063243 0.91071345 0.03043927]
 [0.67256103 0.07133969 0.36078049 0.41809954]
 [0.18140429 0.5210141  0.53499176 0.31704388]]
matrix A^T:
[[0.6096148  0.27721958 0.67256103 0.18140429]
 [0.87262718 0.12063243 0.07133969 0.5210141 ]
 [0.02390303 0.91071345 0.36078049 0.53499176]
 [0.27159522 0.03043927 0.41809954 0.31704388]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [59]:
a = np.random.randint(1, 11, (3, 4))
b = np.random.randint(1, 11, 4)
print(f'matrix A:\n{a}')
print(f'vector b:\n{b}')
print(f'multiplication:\n{np.dot(a,b)}')

matrix A:
[[ 9  6  3 10]
 [ 7  3  6  8]
 [ 8  6  6  7]]
vector b:
[1 7 5 7]
multiplication:
[136 114 129]


11. Cтворіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [60]:
a = np.random.random((2,3))
b = np.random.random(3)
print(f'matrix A:\n{a}')
print(f'vector b:\n{b}')
print(f'multiplication:\n{np.dot(a,b)}')

matrix A:
[[0.28757994 0.67236922 0.71204879]
 [0.65645029 0.14693032 0.97347557]]
vector b:
[0.95538345 0.42462553 0.59363733]
multiplication:
[0.982953   1.26744354]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [62]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
print(f'matrix A:\n{a}')
print(f'matrix B:\n{b}')
print(f'A*B:\n{a*b}')

matrix A:
[[5 1]
 [4 6]]
matrix B:
[[7 5]
 [1 5]]
A*B:
[[35  5]
 [ 4 30]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [63]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
print(f'matrix A:\n{a}')
print(f'matrix B:\n{b}')
print(f'A*B:\n{np.dot(a,b)}')

matrix A:
[[2 6]
 [3 5]]
matrix B:
[[9 8]
 [6 8]]
A*B:
[[54 64]
 [57 64]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [94]:
a = np.random.randint(1, 101, (5, 5))
print(f'matrix:\n{a}')
print(f'SUM of matrix elements:\n{a.sum()}')

matrix:
[[20 75 45 90 65]
 [89 33 40 49 79]
 [38 40 15 28 52]
 [ 3 82 57  2 67]
 [31 74 88 69 46]]
SUM of matrix elements:
1277


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [75]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
print(f'matrix A:\n{a}')
print(f'matrix B:\n{b}')
print(f'A-B:\n{a-b}')

matrix A:
[[ 4  7  5 10]
 [ 6  8 10 10]
 [ 8  7 10  9]
 [ 9  7  3  3]]
matrix B:
[[ 3  6  2  5]
 [ 2  5 10  6]
 [ 4  6  9  8]
 [ 1  9  6  5]]
A-B:
[[ 1  1  3  5]
 [ 4  3  0  4]
 [ 4  1  1  1]
 [ 8 -2 -3 -2]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [92]:
a = np.random.random((3, 3))
print(f'matrix:\n{a}')
print('Vector:')
print(np.array((a[0,0:].sum(), a[1,0:].sum(), a[2,0:].sum())))

matrix:
[[0.31710713 0.35679469 0.95617933]
 [0.91698537 0.58434863 0.9333677 ]
 [0.8637124  0.3757227  0.11696685]]
Vector:
[1.63008114 2.43470171 1.35640196]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [98]:
a = np.random.randint(1, 11, (3, 4))
print(f'matrix A:\n{a}')
print(f'matrix A^2:\n{a**2}')


matrix A:
[[7 2 1 8]
 [1 8 1 4]
 [1 5 1 9]]
matrix A^2:
[[49  4  1 64]
 [ 1 64  1 16]
 [ 1 25  1 81]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [100]:
a = np.random.randint(1, 51, 4)
print(f'vector a:\n{a}')
print(f'vector sqrt(a):\n{np.sqrt(a)}')

vector a:
[50 14 46 29]
vector sqrt(a):
[7.07106781 3.74165739 6.78232998 5.38516481]
